#### 1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

In [ ]:
import numpy as np
arr = np.array([0,1,2,3,4,5])
print(arr.dtype)

int64


In [ ]:
# Another way
arr = np.arange(0,6)
print(arr.dtype)

int64


#### 2. Given a Numpy array 'arr', check if its data type is float64.
```arr = np.array([1.5, 2.6, 3.7])```

In [ ]:
arr = np.array([1.5, 2.6, 3.7])

if arr.dtype == np.float64:
    print("Yes, the data type of 'arr' is float64.")
else:
    print("No, the data type of 'arr' is not float64.")

Yes, the data type of 'arr' is float64.


#### 3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

In [ ]:
arr = np.array([1,2,3], dtype = np.complex128)
arr

array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
arr = np.array([1+2j,3+4j,5+6j], dtype = np.complex128)
print(arr)

[1.+2.j 3.+4.j 5.+6.j]


In [ ]:
arr.dtype

dtype('complex128')

#### 4. Convert an existing Numpy array 'arr' of integers to float32 data type.

In [ ]:
arr = np.arange(0,6)

arr_float32 = np.asarray(arr, dtype = np.float32)
arr_float32

array([0., 1., 2., 3., 4., 5.], dtype=float32)

In [ ]:
arr_float32 = arr.astype(np.float32)
print(arr_float32)

[0. 1. 2. 3. 4. 5.]


In [ ]:
print(np.float32(arr))

[0. 1. 2. 3. 4. 5.]


#### 5. Given a Numpy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

In [ ]:
arr = np.array([1,2,3,4], dtype="float64")
arr

array([1., 2., 3., 4.])

In [ ]:
print(arr.dtype)

float64


In [ ]:
a = np.float32(arr)
print(a.dtype)

float32


#### 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.

In [ ]:
array_attributes = np.array([[1, 2, 3], [4, 5, 6]])
shape, size, dtype = array_attributes.shape, array_attributes.size, array_attributes.dtype
print("Shape:", shape)
print("Size:", size)
print("Data type:", dtype)

Shape: (2, 3)
Size: 6
Data type: int64


#### 7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

In [ ]:
array_dimension = np.array([[1, 2, 3], [4, 5, 6]])

dim = array_dimension.ndim
print("Dimensionality:", dim)

Dimensionality: 2


#### 8. Design a function item_size_info that takes a Numpy array as input and returns the item size and the total size in bytes.

In [ ]:
item_size_info = np.array([[1, 2, 3], [4, 5, 6]])

item_size = item_size_info.size
total_size_in_bytes = item_size_info.itemsize

print("Item size:", item_size)
print("Total size in bytes:", total_size_in_bytes)

Item size: 6
Total size in bytes: 8


In [ ]:
item_size_info = np.array([[1, 2, 3], [4, 5, 6]])

print("Item size:", item_size_info.size)
print("Total size in bytes:", item_size_info.itemsize)

Item size: 6
Total size in bytes: 8


#### 9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

In [ ]:
array_strides = np.array([[1, 2, 3], [4, 5, 6]])

print("Strides of the array:", array_strides.strides)

Strides of the array: (24, 8)


#### 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

In [ ]:
shape_stride_relationship = np.array([[1, 2, 3], [4, 5, 6]])

print("Shape of the array:", shape_stride_relationship.shape)
print("Strides of the array:", shape_stride_relationship.strides)

Shape of the array: (2, 3)
Strides of the array: (24, 8)


#### 11. Create a function 'create_zeros_array' that takes an integer 'n' as input and returns a NumPy array of zeros with 'n' elements.

In [ ]:
create_zeros_array = np.zeros(5)
create_zeros_array

array([0., 0., 0., 0., 0.])

#### 12. Write a function 'create_ones_matrix' that takes Integers 'rows' and 'cols' as inputs and generates a 2D NumPy array filled with ones of size 'rows x cols'.

In [ ]:
create_ones_matrix = np.ones((3,4))
create_ones_matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### 13. Write a function 'generate_range_array' that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from 'start', ending at stop (exclusive), and with the specified 'step'.

In [ ]:
generate_range_array = np.arange(0, 30, 5)
generate_range_array

array([ 0,  5, 10, 15, 20, 25])

In [ ]:
generate_range_array = np.arange(1, 30, 5)
generate_range_array

array([ 1,  6, 11, 16, 21, 26])

#### 14. Design a function 'generate_linear_space' that takes two floats 'start', 'stop', and an integer 'num' as arguments and generates a NumPy array with num equally spaced values between 'start' and 'stop' (inclusive).

In [ ]:
generate_linear_space = np.arange(1.5, 20.8, step = 2)
generate_linear_space

array([ 1.5,  3.5,  5.5,  7.5,  9.5, 11.5, 13.5, 15.5, 17.5, 19.5])

#### 15. Create a function 'create_identity_matrix' that takes an integer 'n' as input and generates a square identity matrix of size 'n x n' using 'numpy.eye'.

In [ ]:
create_identity_matrix = np.eye(4)
create_identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### 16. Write a function that takes a Python list and converts it into a NumPy array.

In [ ]:
list1 = [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

arr = np.array(list1)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

#### 17. Create a NumPy array and demonstrate the use of 'numpy.view' to create a new array object with the same data.

Here's an example of creating a NumPy array and using ```numpy.view``` to create a new array object with the same data:

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

arr_view = arr.view()

print("Original array:")
print(arr)

print("\nView array:")
print(arr_view)

Original array:
[[1 2 3]
 [4 5 6]]

View array:
[[1 2 3]
 [4 5 6]]


In [ ]:
# Modify the view array
arr_view[0, 0] = 100

# Print both arrays again to see the changes
print("\nAfter modifying the view array:")
print("Original array:")
print(arr)

print("\nView array:")
print(arr_view)


After modifying the view array:
Original array:
[[100   2   3]
 [  4   5   6]]

View array:
[[100   2   3]
 [  4   5   6]]


#### 18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

concatenate_array = np.concatenate((arr1, arr2), axis=0)
print("Concatenate along axis 0:")
print(concatenate_array)

Concatenate along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

concatenate_array = np.concatenate((arr1, arr2), axis=1)
print("Concatenate along axis 1:")
print(concatenate_array)

Concatenate along axis 1:
[[1 2 5 6]
 [3 4 7 8]]


#### 19. Create two NumPy arrays with different shapes and concatenate them horizontally using 'numpy.concatenate'.

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5], [6]])

concatenate_array = np.concatenate((arr1, arr2), axis=1)
print("Concatenate horizontally:")
print(concatenate_array)

Concatenate horizontally:
[[1 2 5]
 [3 4 6]]


In [ ]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8], [9, 10]])

concatenate_array = np.concatenate((arr1, arr2), axis=1)
print("Concatenate horizontally:")
print(concatenate_array)

Concatenate horizontally:
[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


#### 20. Write a function that vertically stacks multiple NumPy arrays given as a list.

In [ ]:
arr1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

arr2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

stacked_array = np.vstack([arr1, arr2])
print("Stacked array:")
print(stacked_array)

Stacked array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
import numpy as np

arr1 = np.array([[1, 2, 3],
                   [4, 5, 6]])
arr2 = np.array([[7, 8, 9],
                   [10, 11, 12]])
arr3 = np.array([[13, 14, 15],
                   [16, 17, 18]])

stacked_array = np.vstack([arr1, arr2, arr3])
print("Stacked array:")
print(stacked_array)

Stacked array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


#### 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.

In [ ]:
def create_array(start, stop, step):
    return np.arange(start, stop + 1, step, dtype=int)

start = 1
stop = 10
step = 2
result = create_array(start, stop, step)
print(result)

[1 3 5 7 9]


In [ ]:
def create_array(start, stop, step):
    return np.arange(start, stop + 1, step, dtype=int)

result = create_array(0, 20, 4)
print(result)

[ 0  4  8 12 16 20]


#### 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

In [ ]:
arr = np.linspace(0, 1, 10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
def generate_array():
  return np.linspace(0, 1, 10)

result = generate_array()
print(result)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


#### 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

In [ ]:
log_spaced_array = np.logspace(np.log10(1), np.log10(1000), 5)
log_spaced_array

array([   1.        ,    5.62341325,   31.6227766 ,  177.827941  ,
       1000.        ])

In [ ]:
def log_spaced_array(start, end, num):
  return np.logspace(np.log10(start), np.log10(end), num)

result = log_spaced_array(1, 1000, 5)
print(result)

[   1.            5.62341325   31.6227766   177.827941   1000.        ]


#### 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.

In [ ]:
import random
import pandas as pd

df = pd.DataFrame(np.random.randint(1, 101, size = (5,3)))
df

0   1   2
0  42  63  78
1  75  41  90
2  15  47  24
3   4   9  11
4  17  96  89

In [ ]:
random_array = np.random.randint(1, 101, size = (5,3))

df = pd.DataFrame(random_array, columns = ['Column 1', 'Column 2', 'Column 3'])
df

Column 1  Column 2  Column 3
0        54        99        51
1        78        74        89
2        19         4        79
3        50        77        27
4        64        49        10

#### 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
def replace_negatives_with_zeros(df, column_name):
  df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
  return df

# Example usage:
df = pd.DataFrame({'A': [-1, 2, -3, 4, -5], 'B': [5, -6, 7, -8, 9], 'C': [0, 1, -2, 3, -4]})
df = replace_negatives_with_zeros(df, 'A')

print(df)

   A  B  C
0  0  5  0
1  2 -6  1
2  0  7 -2
3  4 -8  3
4  0  9 -4


#### 26. Access the 3rd element from the given NumPy array.
```arr = np.array([10, 20, 30, 40, 50])```

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
arr[2]

30

#### 27. Retrieve the element at Index (1, 2) from the 2D NumPy array.
```arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])```

In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr_2d[1, 2]

6

#### 28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
```arr = np.array([3, 8, 2, 10, 5, 7])```

In [ ]:
arr = np.array([3, 8, 2, 10, 5, 7])
result = arr[arr > 5]
print(result)

[ 8 10  7]


#### 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
```arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])```

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
sliced_arr = arr[2:6]
print(sliced_arr)

[3 4 5 6]


#### 30. Slice the 2D NumPy array to extract the sub-array ```[[2, 3], [5, 6]]``` from the given array.
```arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])```

In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
sub_arr_2d = arr_2d[0:2, 1:3]
print(sub_arr_2d)

[[2 3]
 [5 6]]


#### 31. Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.

In [ ]:
def extract_elements(arr, indices):
  rows = np.arange(arr.shape[0])
  extracted_elements = arr[rows[:, np.newaxis], indices]
  return extracted_elements

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

indices = np.array([1, 0, 2])

extracted = extract_elements(arr, indices)
print(extracted)

[[2 1 3]
 [5 4 6]
 [8 7 9]]


In [ ]:
# another way

def extract_elements(arr, indices):
  return arr[np.arange(arr.shape[0])[:, None], indices]

arr = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
indices = np.array([1, 2, 0])

result = extract_elements(arr, indices)
print(result)

[[2 3 1]
 [5 6 4]
 [8 9 7]]


#### 32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

In [ ]:
random_array = np.random.randint(0, 100, 20)
random_array

array([69, 76, 81, 91, 43, 58, 25, 86, 50, 79, 84, 15, 20,  2, 15, 47, 58,
       53, 16, 93])

In [ ]:
random_array > 50

array([ True,  True,  True,  True, False,  True, False,  True, False,
        True,  True, False, False, False, False, False,  True,  True,
       False,  True])

In [ ]:
def filter_greater_than_threshold(array, threshold):
    return array[array > threshold]

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
threshold = 5
result = filter_greater_than_threshold(array, threshold)
print(result)

[6 7 8 9]


#### 33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.

In [ ]:
def extract_elements(array, indices_dim1, indices_dim2, indices_dim3):
    return array[indices_dim1, indices_dim2, indices_dim3]

# Example usage:
array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
indices_dim1 = np.array([[0, 0], [1, 1]])
indices_dim2 = np.array([[0, 1], [1, 1]])
indices_dim3 = np.array([[1, 1], [0, 1]])

result = extract_elements(array, indices_dim1, indices_dim2, indices_dim3)
print(result)

[[ 2  5]
 [10 11]]


In [ ]:
def extract_elements(array, indices_dim1, indices_dim2, indices_dim3):
    return array[indices_dim1, indices_dim2, indices_dim3]

# Example usage:
array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
indices_dim1 = np.array([[0, 0], [1, 1]])
indices_dim2 = np.array([[0, 1], [0, 1]])
indices_dim3 = np.array([[0, 2], [1, 2]])

result = extract_elements(array, indices_dim1, indices_dim2, indices_dim3)
print(result)

[[ 1  6]
 [ 8 12]]


#### 34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

condition1 = arr > 3
condition2 = arr % 2 == 0

result = arr[condition1 & condition2]

print(result)

[4 6 8]


#### 35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

In [ ]:
def extract_elements(array, row_indices, col_indices):
    return array[row_indices, col_indices]

# Example usage:
array = np.array([[1, 2, 3], [4, 5, 6]])
row_indices = np.array([[0, 0], [1, 1]])
col_indices = np.array([[0, 1], [1, 1]])

result = extract_elements(array, row_indices, col_indices)
print(result)

[[1 2]
 [5 5]]


In [ ]:
def extract_elements(array, row_indices, col_indices):
    return array[row_indices, col_indices]

# Example usage:
array = np.array([[1, 2, 3], [4, 5, 6]])
row_indices = np.array([0, 0])
col_indices = np.array([0, 1])

result = extract_elements(array, row_indices, col_indices)
print(result)

[1 2]


In [ ]:
def extract_elements(array, row_indices, col_indices):
    return array[row_indices, col_indices]

# Example usage:
array = np.array([[1, 2, 3], [4, 5, 6]])
row_indices = np.array([0, 0, 1])
col_indices = np.array([0, 1, 1])

result = extract_elements(array, row_indices, col_indices)
print(result)

[1 2 5]


In [ ]:
def extract_elements(array, row_indices, col_indices):
    return array[row_indices, col_indices]

# Example usage:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_indices = np.array([0, 2, 1])
col_indices = np.array([1, 1, 1])

result = extract_elements(array, row_indices, col_indices)
print(result)

[2 8 5]


In [ ]:
def extract_elements(array, row_indices, col_indices):
    return array[row_indices, col_indices]

# Example usage:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_indices = np.array([[0, 2], [0, 1]])
col_indices = np.array([[0, 1], [1, 0]])

result = extract_elements(array, row_indices, col_indices)
print(result)

[[1 8]
 [2 4]]


#### 36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

In [ ]:
arr = np.random.randint(0, 50, size = (3,3))
arr

array([[44, 32,  7],
       [40, 36, 10],
       [47, 41, 31]])

In [ ]:
print(arr + 5)

[[49 37 12]
 [45 41 15]
 [52 46 36]]


#### 37. Consider two arrays arr1 of shape (1,3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.

In [ ]:
arr1 = np.random.randint(0, 10, size = (1,3))
arr1

array([[4, 2, 7]])

In [ ]:
arr2 = np.random.randint(0, 10, size = (3,4))
arr2

array([[5, 2, 5, 4],
       [9, 6, 7, 2],
       [3, 3, 5, 8]])

In [ ]:
result = arr2 * arr1.T # Transpose arr1 to broadcast along the rows
print(result)

[[20  8 20 16]
 [18 12 14  4]
 [21 21 35 56]]


In [ ]:
# another way using reshape
arr1_reshaped = arr1.reshape(-1,1)
result = arr1_reshaped * arr2
print(result)

[[20  8 20 16]
 [18 12 14  4]
 [21 21 35 56]]


#### 38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

In [ ]:
arr1 = np.random.randint(0, 10, size = (1,4))
arr1

array([[8, 8, 6, 7]])

In [ ]:
arr2 = np.random.randint(0, 10, size = (4,3))
arr2

array([[0, 5, 3],
       [9, 0, 9],
       [1, 2, 7],
       [4, 4, 0]])

In [ ]:
arr1.T + arr2

array([[ 8, 13, 11],
       [17,  8, 17],
       [ 7,  8, 13],
       [11, 11,  7]])

#### 39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

In [ ]:
import numpy as np
arr1 = np.random.randint(0, 10, size = (3,1))
arr1

array([[4],
       [2],
       [4]])

In [ ]:
arr2 = np.random.randint(0, 10, size = (1,3))
arr2

array([[5, 1, 5]])

In [ ]:
arr1 + arr2

array([[9, 5, 9],
       [7, 3, 7],
       [9, 5, 9]])

#### 40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.

In [ ]:
arr1 = np.random.randint(0, 10, size = (2,3))
arr1

array([[3, 6, 7],
       [4, 0, 8]])

In [ ]:
arr2 = np.random.randint(0, 10, size = (2,2))
arr2

array([[8, 2],
       [6, 9]])

In [ ]:
arr2_reshaped = arr2[:, :, np.newaxis]
arr2_reshaped

array([[[8],
        [2]],

       [[6],
        [9]]])

In [ ]:
arr1 * arr2_reshaped

array([[[24, 48, 56],
        [ 8,  0, 16]],

       [[18, 36, 42],
        [36,  0, 72]]])

In [ ]:
# another way
arr1_reshaped = arr1[:, :, np.newaxis]
arr1_reshaped

array([[[3],
        [6],
        [7]],

       [[4],
        [0],
        [8]]])

In [ ]:
arr2_reshaped = arr2[:, np.newaxis, :]
arr2_reshaped

array([[[8, 2]],

       [[6, 9]]])

In [ ]:
arr1_reshaped * arr2_reshaped

array([[[24,  6],
        [48, 12],
        [56, 14]],

       [[24, 36],
        [ 0,  0],
        [48, 72]]])

#### 41. Calculate column-wise mean for the given array:
```arr = np.array([[1, 2, 3], [4, 5, 6]])```

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.mean(arr, axis = 0)

array([2.5, 3.5, 4.5])

#### 42. Find maximum value in each row of the given array:
```arr = np.array([[1, 2, 3], [4, 5, 6]])```

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.max(arr, axis = 1)

array([3, 6])

#### 43. For the given array, find indices of maximum value in each column,
```arr = np.array([[1, 2, 3], [4, 5, 6]])```

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.argmax(arr, axis = 0)

array([1, 1, 1])

#### 44. For the given array, apply custom function to calculate moving sum along rows.
```arr = np.array([[1, 2, 3], [4, 5, 6]])```

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

moving_sum = np.cumsum(arr, axis=1)
print(moving_sum)

[[ 1  3  6]
 [ 4  9 15]]


#### 45. In the given array, check if all elements in each column are even.
```arr = np.array([[2, 4, 6], [3, 5, 7]])```

In [ ]:
arr = np.array([[2, 4, 6], [3, 5, 7]])

all_even = np.all(arr%2 == 0, axis=0)
print(all_even)

[False False False]


#### 46. Given a NumPy array arr, reshape it into a matrix of dimensions 'm' rows and 'n' columns. Return the reshaped matrix.
```original_array = np.array([1, 2, 3, 4, 5, 6])```

In [ ]:
original_array = np.array([1, 2, 3, 4, 5, 6])

reshaped_array = original_array.reshape(2,3)
print(reshaped_array)

[[1 2 3]
 [4 5 6]]


In [ ]:
reshaped_array = original_array.reshape(3,2)
print(reshaped_array)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
reshaped_array = original_array.reshape(1,6)
print(reshaped_array)

[[1 2 3 4 5 6]]


In [ ]:
reshaped_array = original_array.reshape(6,1)
print(reshaped_array)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


#### 47. Create a function that takes a matrix as input and returns the flattened array.
```input_matrix = np.array([[1, 2, 3], [4, 5, 6]])```

In [ ]:
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
input_matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
input_matrix.flatten()

array([1, 2, 3, 4, 5, 6])

#### 48. Write a function that concatenates two given arrays along a specified axis.
```array1 = np.array([[1, 2], [3, 4]])```

```array2 = np.array([[5, 6], [7, 8]])```

In [ ]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

np.concatenate((array1, array2),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

np.concatenate((array1, array2),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

#### 49. Create a function that splits an array into multiple sub-arrays along a specified axis.
```original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])```

In [ ]:
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.split(original_array, 3, axis=1)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [ ]:
np.split(original_array, 3, axis=0)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

#### 50. Write a function that inserts and then deletes elements from a given array at specified indices.
```original_array = np.array([1, 2, 3, 4, 5])```

```indices_to_insert = [2,4]```

```values_to_insert = [10, 11]```

```indices_to_delete = [1, 3]```

In [ ]:
import numpy as np

In [ ]:
def insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete):

  # Insert elements
  for index, value in zip(indices_to_insert, values_to_insert):
      original_array = np.insert(original_array, index, value)

  # Delete elements
  original_array = np.delete(original_array, indices_to_delete)
  return original_array

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

result_array = insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print(result_array)

[ 1 10 11  4  5]


#### 51. Create a NumPy array 'arr1' with random integers and another array 'arr2' with integers from 1 to 10. Perform element-wise addition between 'arr1' and 'arr2'.

In [ ]:
arr1 = np.random.randint(1, 11, 5)
arr2 = np.random.randint(1, 11, 5)

In [ ]:
arr1

array([1, 2, 4, 5, 6])

In [ ]:
arr2

array([9, 1, 8, 7, 1])

In [ ]:
arr1 + arr2

array([10,  3, 12, 12,  7])

In [ ]:
arr1 = np.random.randint(1, 11, (2,3))
arr2 = np.random.randint(1, 11, (2,3))

In [ ]:
arr1

array([[ 2,  1,  1],
       [ 5,  2, 10]])

In [ ]:
arr2

array([[4, 8, 3],
       [2, 5, 9]])

In [ ]:
arr1 + arr2

array([[ 6,  9,  4],
       [ 7,  7, 19]])

#### 52. Generate a NumPy array 'arr1' with sequential integers from 10 to 1 and another array 'arr2' with integers from 1 to 10. Subtract 'arr2' from 'arr1' element-wise.

In [ ]:
arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)

In [ ]:
arr1

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [ ]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr1 - arr2

array([ 9,  7,  5,  3,  1, -1, -3, -5, -7, -9])

#### 53. Create a NumPy array 'arr1' with random integers and another array 'arr2' with integers from 1 to 5. Perform element-wise multiplication between 'arr1' and 'arr2'.

In [ ]:
arr1 = np.random.randint(1, 6, 5)
arr2 = np.random.randint(1, 6, 5)

In [ ]:
arr1

array([4, 5, 4, 2, 2])

In [ ]:
arr2

array([1, 5, 4, 5, 3])

In [ ]:
arr1 * arr2

array([ 4, 25, 16, 10,  6])

#### 54. Generate a NumPy array 'arr1' with even integers from 2 to 10 and another array 'arr2' with integers from 1 to 5. Perform element-wise division of 'arr1' by 'arr2'.

In [ ]:
arr1 = np.arange(2, 11, 2)
arr2 = np.arange(1, 6)

In [ ]:
arr1

array([ 2,  4,  6,  8, 10])

In [ ]:
arr2

array([1, 2, 3, 4, 5])

In [ ]:
arr1 / arr2

array([2., 2., 2., 2., 2.])

#### 55. Create a NumPy array 'arr1' with integers from 1 to 5 and another array 'arr2' with the same numbers reversed. Calculate the exponentiation of 'arr1' raised to the power of 'arr2' element-wise.

In [ ]:
arr1 = np.arange(1, 6)
arr2 = np.arange(5, 0, -1)

In [ ]:
arr1

array([1, 2, 3, 4, 5])

In [ ]:
arr2

array([5, 4, 3, 2, 1])

In [ ]:
np.power(arr1, arr2)

array([ 1, 16, 27, 16,  5])

In [ ]:
# another way
arr1 = np.arange(1, 6)
arr2 = np.flip(arr1)

In [ ]:
arr1

array([1, 2, 3, 4, 5])

In [ ]:
arr2

array([5, 4, 3, 2, 1])

In [ ]:
np.power(arr1, arr2)

array([ 1, 16, 27, 16,  5])

In [ ]:
# or
arr1 ** arr2

array([ 1, 16, 27, 16,  5])

#### 56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
```arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])```

In [ ]:
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
np.char.count(arr, 'hello')

array([1, 0, 1, 0, 1])

In [ ]:
def count_substring_occurrences(arr, substring):
  return sum(1 for string in arr if substring in string)

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'
occurrences = count_substring_occurrences(arr, substring)

print("Occurrences of '{}' in the array: {}".format(substring, occurrences))

Occurrences of 'hello' in the array: 3


#### 57. Write a function that extracts uppercase characters from a NumPy array of strings.
```arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'))```

In [ ]:
def extract_uppercase(arr):
  uppercase_chars = np.array([''.join(filter(str.isupper, s)) for s in arr])
  return uppercase_chars

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
uppercase_chars = extract_uppercase(arr)
print(uppercase_chars)

['H' 'W' 'OAI' 'GPT']


#### 58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
```arr = np.array(['apple', 'banana', 'grape', 'pineapple'])```

In [ ]:
def replace_substring(arr, old_substring, new_substring):
    return np.char.replace(arr, old_substring, new_substring)

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
new_arr = replace_substring(arr, 'apple', 'orange')

print(new_arr)

['orange' 'banana' 'grape' 'pineorange']


In [ ]:
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
np.char.replace(arr, 'a', 'x')

array(['xpple', 'bxnxnx', 'grxpe', 'pinexpple'], dtype='<U9')

#### 59. Write a function that concatenates strings in a NumPy array element-wise.
```arr1 = np.array(['Hello', 'World'])```

```arr2 = np.array(['Open', 'AI'])```

In [ ]:
def concatenate_strings(arr1, arr2):
    return np.char.add(arr1, arr2)

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

result = concatenate_strings(arr1, arr2)
print(result)

['HelloOpen' 'WorldAI']


In [ ]:
# another way

def concatenate_strings(arr1, arr2):
    return np.core.defchararray.add(arr1, arr2)

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

concatenated_array = concatenate_strings(arr1, arr2)
print(concatenated_array)

['HelloOpen' 'WorldAI']


#### 60. Write a function that finds the length of the longest string in a NumPy array.
```arr = np.array(['apple', 'banana', 'grape', 'pineapple'])```

In [ ]:
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
max(np.vectorize(len)(arr))

9

In [ ]:
# another way

def longest_string_length(arr):
    return max(len(s) for s in arr)

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
print(longest_string_length(arr))

9


In [ ]:
# another way

def longest_string_length(arr):
    return max(map(len, arr))

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
print(longest_string_length(arr))

9


#### 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.

In [ ]:
dataset = np.random.randint(1, 1001, 100)

# Compute mean, median, variance, and standard deviation
mean = np.mean(dataset)
median = np.median(dataset)
variance = np.var(dataset)
std_dev = np.std(dataset)

print("Dataset:", dataset)
print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_dev)

Dataset: [526 201 281 574 367 636 811 117 570 474 590 821 260 221 625 370 693 260
 821 489 308 355 459  96 571  23  73 355 195 714 857 141  95 380 960   5
 286 626 714 664 673 460  86 331 167 945 140 478 663 433  96 935 490 463
  15 485 577  19 304 218   3 763 392 920 738 896 592 314 256 158 501 784
 766 255 861 707 979 685 657 230 222  42 121 228 456 495  50 294 374 192
 671 595 991 248 382 186 360 335 852  67]
Mean: 441.8
Median: 412.5
Variance: 73954.7
Standard Deviation: 271.9461343722319


#### 62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

In [ ]:
random_numbers = np.random.randint(1, 101, 50)

# Find the 25th and 75th percentiles
percentile_25 = np.percentile(random_numbers, 25)
percentile_75 = np.percentile(random_numbers, 75)

print("25th percentile:", percentile_25)
print("75th percentile:", percentile_75)

25th percentile: 24.5
75th percentile: 71.25


#### 63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's 'corrcoef' function.

In [ ]:
array1 = np.random.rand(100)
array2 = np.random.rand(100)

correlation_coefficient = np.corrcoef(array1, array2)[0, 1]

print("Correlation Coefficient:", correlation_coefficient)

Correlation Coefficient: 0.06351982386046869


#### 64. Create two matrices and perform matrix multiplication using NumPy's 'dot' function.

In [ ]:
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6]])

matrix2 = np.array([[7, 8],
                    [9, 10],
                    [11, 12]])

result = np.dot(matrix1, matrix2)

print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
print("\nResult of matrix multiplication:")
print(result)

Matrix 1:
[[1 2 3]
 [4 5 6]]

Matrix 2:
[[ 7  8]
 [ 9 10]
 [11 12]]

Result of matrix multiplication:
[[ 58  64]
 [139 154]]


In [ ]:
matrix1 = np.array([[1, 2],
                    [3, 4]])

matrix2 = np.array([[5, 6],
                    [7, 8]])

result = np.dot(matrix1, matrix2)

print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
print("\nResult of matrix multiplication:")
print(result)

Matrix 1:
[[1 2]
 [3 4]]

Matrix 2:
[[5 6]
 [7 8]]

Result of matrix multiplication:
[[19 22]
 [43 50]]


#### 65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

In [ ]:
import numpy as np

arr = np.random.randint(10, 1001, 50)

percentiles = np.percentile(arr, [10, 25, 50, 75, 90])

print("Array:", arr)
print("10th percentile:", percentiles[0])
print("First quartile (25th percentile):", percentiles[1])
print("Median (50th percentile):", percentiles[2])
print("Third quartile (75th percentile):", percentiles[3])
print("90th percentile:", percentiles[4])

Array: [317 352 237 134 773 158 909 506 440 546 270 793  16  87 580  81 407 583
  34 767 116 837 765 412 765 842 242 483 582 806  16 711 619 906 809 602
 942  53 802 633 135 913  30 569 223 553 371 205 627 496]
10th percentile: 78.20000000000002
First quartile (25th percentile): 226.5
Median (50th percentile): 526.0
Third quartile (75th percentile): 765.0
90th percentile: 837.5


#### 66. Create a NumPy array of integers and find the index of a specific element.

In [ ]:
arr = np.random.randint(1, 21, 10)
arr

array([15, 15, 15, 16,  1, 10, 18,  9,  8, 14])

In [ ]:
np.where(arr==15)

(array([0, 1, 2]),)

####67. Generate a random NumPy array and sort it in ascending order.

In [ ]:
arr = np.random.randint(1,11,5)
arr

array([4, 8, 1, 7, 1])

In [ ]:
np.sort(arr)

array([1, 1, 4, 7, 8])

#### 68. Filter elements >20 in the given NumPy array.
```arr = np.array([12, 25, 6, 42, 8, 30])```

In [ ]:
arr = np.array([12, 25, 6, 42, 8, 30])

arr[arr>20]

array([25, 42, 30])

#### 69. Filter elements which are divisible by 3 from a given NumPy array.
```arr = np.array([1, 5, 8, 12, 15])```

In [ ]:
arr = np.array([1, 5, 8, 12, 15])

arr[arr%3 == 0]

array([12, 15])

#### 70. Filter elements which are >= 20 and <= 40 from a given NumPy array.
```arr = np.array([10, 20, 30, 40, 50])```

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

arr[(arr>=20) & (arr<=40)]

array([20, 30, 40])

#### 71. For the given NumPy array, check its byte order using the 'dtype' attribute byteorder.
```arr = np.array([1, 2, 3])```

In [ ]:
arr = np.array([1, 2, 3])

arr.dtype.byteorder

'='

#### 72. For the given NumPy array, perform byte swapping in place using 'byteswap()'.
```arr = np.array([1, 2, 3], dtype=np.int32)```

In [ ]:
arr = np.array([1, 2, 3], dtype=np.int32)

arr.byteswap()

array([16777216, 33554432, 50331648], dtype=int32)

#### 73. For the given NumPy array, swap its byte order without modifying the original array using 'newbyteorder()'.
```arr = np.array([1, 2, 3], dtype=np.int32)```

In [ ]:
arr = np.array([1, 2, 3], dtype=np.int32)
arr.newbyteorder()

array([16777216, 33554432, 50331648], dtype='>i4')

#### 74. For the given NumPy array and swap its byte order conditionally based on system endianness using 'newbyteorder()'.
```arr = np.array([1, 2, 3], dtype=np.int32)```

In [ ]:
import numpy as np
import sys

arr = np.array([1, 2, 3], dtype=np.int32)
arr.newbyteorder(sys.byteorder)

array([1, 2, 3], dtype=int32)

#### 75. For the given NumPy array, check if byte swapping is necessary for the current system using 'dtype' attribute 'byteorder'.
```arr = np.array([1, 2, 3], dtype=np.int32)```

In [ ]:
arr = np.array([1, 2, 3], dtype=np.int32)

byte_order = arr.dtype.byteorder

if byte_order == '=':
    print("No byte swapping is necessary for the current system.")
else:
    print("Byte swapping is necessary for the current system.")

No byte swapping is necessary for the current system.


In [ ]:
# another way

arr = np.array([1, 2, 3], dtype=np.int32)

byte_order = arr.dtype.byteorder

if byte_order == '|':
    print("Byte swapping is necessary for the current system.")
else:
    print("No byte swapping is necessary for the current system.")

No byte swapping is necessary for the current system.


#### 76. Create a NumPy array 'arr1' with values from 1 to 10. Create a copy of 'arr1' named 'copy_arr' and modify an element in 'copy_arr'. Check if modifying 'copy_arr' affects 'arr1'.

In [ ]:
arr1 = np.arange(1, 11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
copy_arr = arr1.copy()
copy_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
copy_arr[0] = 100
copy_arr

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [ ]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

We can see, modifying 'copy_arr' did not affect 'arr1'.

#### 77. Create a 2D NumPy array 'matrix' of shape (3, 3) with random integers. Extract a slice 'view_slice' from the matrix. Modify an element in 'view_slice' and observe if it changes the original 'matrix'.

In [ ]:
matrix = np.random.randint(0, 10, size=(3, 3))
print("Original Matrix:")
print(matrix)

view_slice = matrix[:2, :2]
print("\nSlice View:")
print(view_slice)

view_slice[0, 0] = 100

print("\nModified Matrix:")
print(matrix)

Original Matrix:
[[8 7 3]
 [9 9 0]
 [9 7 6]]

Slice View:
[[8 7]
 [9 9]]

Modified Matrix:
[[100   7   3]
 [  9   9   0]
 [  9   7   6]]


#### 78. Create a NumPy array 'array_a' of shape (4, 3) with sequential integers from 1 to 12. Extract a slice 'view_b' from 'array_a' and broadcast the addition of 5 to 'view_b'. Check if it alters the original 'array_a'.

In [ ]:
array_a = np.arange(1, 13).reshape(4, 3)
array_a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
view_b = array_a[1:3, 1:3]
view_b

array([[5, 6],
       [8, 9]])

In [ ]:
view_b += 5
view_b

array([[10, 11],
       [13, 14]])

In [ ]:
array_a

array([[ 1,  2,  3],
       [ 4, 10, 11],
       [ 7, 13, 14],
       [10, 11, 12]])

#### 79. Create a NumPy array 'orig_array' of shape (2, 4) with values from 1 to 8. Create a reshaped view 'reshaped_view' of shape (4, 2) from orig_array. Modify an element in 'reshaped_view' and check if it reflects changes in the original 'orig_array'.

In [ ]:
orig_array = np.arange(1, 9).reshape(2, 4)
orig_array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
reshaped_view = orig_array.reshape(4, 2)
reshaped_view

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
reshaped_view[3,1] = 100
reshaped_view

array([[  1,   2],
       [  3,   4],
       [  5,   6],
       [  7, 100]])

In [ ]:
orig_array

array([[  1,   2,   3,   4],
       [  5,   6,   7, 100]])

#### 80. Create a NumPy array 'data' of shape (3, 4) with random integers. Extract a copy 'data_copy' of elements greater than 5. Modify an element in 'data_copy' and verify if it affects the original 'data'.

In [ ]:
data = np.random.randint(1, 21, (3,4))
data

array([[18, 19,  1, 13],
       [12,  3, 18, 20],
       [ 8,  7,  1, 11]])

In [ ]:
data_copy = np.copy(data[data>5])
data_copy

array([18, 19, 13, 12, 18, 20,  8,  7, 11])

In [ ]:
data_copy[0] = 100
data_copy

array([100,  19,  13,  12,  18,  20,   8,   7,  11])

In [ ]:
data

array([[18, 19,  1, 13],
       [12,  3, 18, 20],
       [ 8,  7,  1, 11]])

We can see that modifying an element in 'data_copy' does not affect the original 'data'.

#### 81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

In [ ]:
A = np.random.randint(0,10, (2,3))
B = np.random.randint(0,10, (2,3))

In [ ]:
A

array([[0, 2, 7],
       [4, 0, 3]])

In [ ]:
B

array([[9, 8, 5],
       [3, 4, 1]])

In [ ]:
# Addition operation
A+B

array([[ 9, 10, 12],
       [ 7,  4,  4]])

In [ ]:
# Subtraction operation
A-B

array([[-9, -6,  2],
       [ 1, -4,  2]])

#### 82. Generate two matrices 'C' (3x2) and 'D' (2x4) and perform matrix multiplication.

In [ ]:
C = np.random.randint(0,10, (3,2))
D = np.random.randint(0,10, (2,4))

In [ ]:
C

array([[4, 0],
       [4, 1],
       [6, 8]])

In [ ]:
D

array([[8, 4, 9, 4],
       [6, 2, 4, 6]])

In [ ]:
C @ D # Returns dot product

array([[32, 16, 36, 16],
       [38, 18, 40, 22],
       [96, 40, 86, 72]])

In [ ]:
# Matrix multiplication with dot product
np.dot(C, D)

array([[32, 16, 36, 16],
       [38, 18, 40, 22],
       [96, 40, 86, 72]])

#### 83. Create a matrix 'E' and find its transpose.

In [ ]:
E = np.random.randint(0,10, (3,2))
E

array([[8, 8],
       [9, 7],
       [5, 9]])

In [ ]:
# Transpose of E
E.T

array([[8, 9, 5],
       [8, 7, 9]])

#### 84. Generate a square matrix 'F' and compute its determinant.

In [ ]:
F = np.random.randint(0,10, (3,3))
F

array([[4, 8, 1],
       [1, 9, 3],
       [9, 5, 6]])

In [ ]:
# Compute determinant
np.linalg.det(F)

247.99999999999986

#### 85. Create a square matrix 'G' and find its inverse.

In [ ]:
G = np.random.randint(0,10, (3,3))
G

array([[6, 5, 1],
       [9, 5, 9],
       [4, 4, 8]])

In [ ]:
# Find inverse of G
np.linalg.inv(G)

array([[-0.02857143,  0.25714286, -0.28571429],
       [ 0.25714286, -0.31428571,  0.32142857],
       [-0.11428571,  0.02857143,  0.10714286]])